name: Playwright Tests
on:
  push:
    branches: [next]
  pull_request:
    branches: [next]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node / npm env and install deps
        uses: ./.github/workflows/reusable/env-setup

      - name: Warmup pm2
        run: npx pm2 list

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run start:e2e

      - name: Cleanup
        if: always()
        run: npm run stop:e2e
        
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-results
          path: playwright-results/
          retention-days: 30
