name: 'Code release'

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/reusable/env-setup
      - name: Check versioning
        run: yarn version check
      - name: Build libs
        run: yarn build:libs
      - name: Build demos
        run: yarn build:demos
      
